[project]
name = 'sbtc-pay'
description = 'Enterprise-grade sBTC payment infrastructure with invoices, refunds, and subscriptions'
authors = []
telemetry = true
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'ST1F7QA2MDF17S807EPA36TSS8AMEFY4KA9TVGWXT.sbtc-token'

[[project.requirements]]
contract_id = 'SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-token'

[contracts.payment-v6]
#path = 'contracts/payment-v6.clar'
#clarity_version = 4
#epoch = 'latest'

[contracts.sbtc-pay]
path = 'contracts/sbtc-pay-mainnet.clar'
clarity_version = 4
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
